### ISSUE TITLE
Tomighty for Linux 

### ISSUE THREAD

**Issue by leni1** [tomighty/tomighty-osx#42]
I guess this would fall into an enhancement of sorts, but is there a way to get a version that runs on Linux. If so, how would one go about it? I'm happy to compile ad-infinitum or basically do whatever it takes to get one. Thanks.

**Comment by ccidral** [comment]
I started working on a Qt version of Tomighty some time back but I didn't have time to finish it. Qt looks very promising when it comes to cross platform GUI apps. Unfortunately I don't have enough time to work on that. But if you're willing to do it under the Tomighty flag, I'd be more than glad to support the effort.

**Comment by leni1** [comment]
Alright. I think that's fair. Should I start from scratch or could you give me the code you'd already written and any associated documentation?

**Comment by ccidral** [comment]
Sure, the unfinished Qt version is here: https://github.com/tomighty/tomighty/tree/develop

One question: last time I checked the tray icon didn't work at all on Ubuntu's Unity. IIRC, Unity completely changed the way it manages tray icons. In case you hit that wall, what do you think we could do to make sure the tray icon works consistently across different desktop environments on Linux?

**Comment by dvntucker** [comment]
Hi @leni1, unfortunately it's unlikely that this version of Tomighty will ever work for Linux because it's inextricably tied to the MacOS/ObjectiveC/Cocoa platform. There has been a Swift conversion in the works for a long time, which I guess at least has the theoretical potential to compile on Linux some day, but even then it depends on the AppKit frameworks and such.

**Comment by dvntucker** [comment]
I'm going to close this issue. Please see the Qt version linked upthread. Cheers.
