### ISSUE TITLE
Raise system notification when timer goes off

### ISSUE THREAD

**Issue by ccidral** [tomighty/tomighty-osx#7]

**Comment by eduardonunesp** [comment]
:+1:

**Comment by eduardonunesp** [comment]
Notifications implemented, if you want give a try https://github.com/eduardonunesp/tomighty-osx

**Comment by dvntucker** [comment]
Any PR for this should include a preference to enable/disable it.

**Comment by russkel** [comment]
👍 Just got this app today and was hoping someone had implemented this!

**Comment by sprig** [comment]
👍  @dvntucker Isn't the choice inside the notification center enough?

**Comment by dvntucker** [comment]
IMO, providing a preference for it is easy enough that I would prefer that any PR for this included it, because in my mind the default should be for no notifications (even though personally I want them). That being said, if someone wants to create a PR with just notifications and no preference for them I'd be willing to either release it as is, or write the preference code myself. 

I even have Notifications created in my own branch, I just haven't had time to rebase it off of current develop. If someone wants to rebase it and create a PR against develop I'd be happy to merge. Otherwise I'll try to get to it ASAP:

https://github.com/dvntucker/tomighty-osx/commit/7523779b41dea26fef0c4351a97b00dac1f82eb1

**Comment by dvntucker** [comment]
Merged. Aiming for release 1.2, should be sometime very soon (hopefully this weekend).
